inventory:
  plugin: NetBoxInventory
  options:
    group_file: automation/inventory/groups.yaml
    defaults_file: automation/inventory/defaults.yaml

runner:
  plugin: threaded
  options:
    num_workers: 10